# exclude = ["contest/genfolders", "templates/stress.py", "tex/preprocessor.py"]

[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++20", "-Wall", "-g", "-fsanitize=address,bounds,undefined", "-D_GLIBCXX_DEBUG"]

